[project]
name = 'Decentralized-Healthcare-Records-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.appointment]
path = 'contracts/appointment.clar'
clarity_version = 2
epoch = 2.5

[contracts.research-data]
path = 'contracts/research-data.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
